name = "nam-portfolio-api"
main = "src/index.js"
compatibility_date = "2024-01-15"

[[d1_databases]]
binding = "DB"
database_name = "nam-portfolio-db"
database_id = "23d9a31f-edb1-431f-ae4b-ea7564dd23d3"

[vars]
ENVIRONMENT = "production"
CORS_ORIGIN = "*"

# 로컬 개발용 설정
[env.dev]
name = "nam-portfolio-api-dev"
vars = { ENVIRONMENT = "development" }

[[env.dev.d1_databases]]
binding = "DB"
database_name = "nam-portfolio-db"
database_id = "local"
